### ISSUE TITLE
`Get-VitalInformation`: Unable to find type `[UInt]`

### ISSUE THREAD

**Issue by jdhitsolutions** [ralish/PSWinVitals#6]
Running in Windows PowerShell 5.1 on Windows 11.

![image](https://user-images.githubusercontent.com/12089920/187214383-d40c494b-7e5e-4373-b3aa-8453e99aab6f.png)

I think you can simply use `[Int]`.

**Comment by ralish** [comment]
Ouch, that's not good. Turns out that PowerShell 5.1 (and earlier presumably) don't have a type accelerator for `UInt`. They do for `UInt32`, and they both resolve to `System.UInt32`, so can use that. I've reviewed the other `[OutputType()]` attributes, and can't see any other types which would have the same issue.

**Comment by ralish** [comment]
I've just published v0.6.7 with a fix for this issue.
